### ISSUE TITLE
bot closes when someone send anything without prefix

### ISSUE THREAD

**Issue by fantalatone** [fantalatone/turtle-dc-bot#2]
```
/home/runner/turtle-dc-bot/events/messageCreate.js:25
        const args = message.content.slice(prefix.length).match(/[^\s"]+|"([^"]*)"/gi).map(a => a.startsWith('"') ? a.substring(1, a.length - 1) : a);
                                                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Client.<anonymous> (/home/runner/turtle-dc-bot/events/messageCreate.js:25:51)
    at Client.emit (node:events:390:28)
    at MessageCreateAction.handle (/home/runner/turtle-dc-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/turtle-dc-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/turtle-dc-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/runner/turtle-dc-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/turtle-dc-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/turtle-dc-bot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/runner/turtle-dc-bot/node_modules/ws/lib/websocket.js:1137:20)
exit status 1
```

that causes by there's no check for bot or prefix on messageCreate event

**Comment by fantalatone** [comment]
fixed with 1.7.0 patch
